---
ci:
  # format compatible with commitlint
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  autoupdate_schedule: quarterly
  autofix_commit_msg: |
    chore: auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-yaml
        files: .*\.(yaml|yml)$
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
  - repo: https://github.com/openstack-dev/bashate.git
    rev: 2.1.0
    hooks:
      - id: bashate
        entry: bashate -i E006
  - repo: https://github.com/pycqa/flake8.git
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-2020>=1.6.0
          # - flake8-docstrings>=1.5.0
          - flake8-pytest-style>=1.2.2
          - flake8-rst-docstrings>=0.2.3
          - flake8-rst>=0.8.0
